config/routes.rb
Rails.application.routes.draw do

	resources :comments, only: [:index, :create]
	get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  resources :users
  devise_for :authors
  devise_for :models
	root to: 'blog/posts#index'


	#espera que a URL possua /author/posts/new ou algo do tipo
	namespace :authors do
		resources :posts do
			put 'publish' => 'posts#publish', on: :member
			put 'unpublish' => 'posts#unpublish', on: :member
		end
	end

	#não espera que a URL possua nada específico, só recebe o comando e executa
	scope module: 'blog' do
		get 'sobre' => 'pages#sobre', as: :sobre
		get 'contato' => 'pages#contato', as: :contato
		get 'posts' => 'posts#index', as: :posts
		get 'posts/:id' => 'posts#show', as: :post
	end


	
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
	acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  
  
end

app/models/post.rb
	# == Schema Information
#
# Table name: posts
#
#  id                 :integer          not null, primary key
#  title              :string
#  body               :text
#  description        :text
#  slug               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  banner_image_url   :string
#  author_id          :integer
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime	
#  published          :boolean          default(FALSE)
#  published_at       :datetime
#

class Post < ApplicationRecord
	acts_as_paranoid
	
	extend FriendlyId
	friendly_id :title, use: :slugged

	belongs_to :author

	scope :most_recent, -> { order(published_at: :desc) }
	scope :published, -> {where(published: true)}

	def should_generate_friendly_id?
		title_changed?
	end

	def display_day_published
		if published_at.present?	
			"Publicado em #{published_at.strftime('%-d/%-b/%Y')}"
		else
			"Ainda não foi publicado."

		end
	end

	def publish
	    update(published: true, published_at: Time.now)
	  end

	  def unpublish
	    update(published: false, published_at: nil)
	  end
  
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |post|
	      csv << post.attributes.values_at(*column_names)
	    end
	  end
	end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	before_action :authenticate_author!, except: [:index, :show]
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url    
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :image, :body, :description, :slug, :banner_image_url)
      end
end

end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_recent.published.paginate(:page => params[:pagina], per_page: 6)
      respond_to do |format|
        format.html
        format.csv { send_data @posts.to_csv }
        format.xls { send_data @posts.to_csv(col_sep: "\t") }
      end
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = Post.friendly.find(params[:id])
    end

   

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    
    <div class="col-md-4">


      <div class="card">
        <div class="card-block">
          <% if @post.new_record? %>
            <h4 class="card-title">Novo Post</h4>
          <% else %>
            <h4 class="card-title">
              <b>Editando</b>
              <span class="thin-text"><%= @post.title %></span>
            </h4>
          <% end %>  
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title, class: 'form-control'%>
            </div>
          </li>

          <li class="list-group-item">
            <div class="field">
              <%= form.label :banner_image_url  %>
              <%= form.file_field :image, class: 'btn-block' %>
            </div>
          </li>

          <li class="list-group-item">
            <div class="field">
              <%= form.label :description %>
              <%= form.text_area :description, class: 'form-control'%>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <div class="actions">
                <%= form.submit 'Atualizar', class: 'btn btn-success btn-block'%>
              </div>
            </div>
          </li>
        </ul>
      </div>

      <% if @post.persisted? %>
        <%= link_to 'Mostrar', authors_post_path(post) %> |
      <% end %>
       <%= link_to 'Voltar', authors_posts_path %>

    </div>



    <div class="col-md-8">
        <div class="field">
          <%= form.text_area :body%>
        </div>
    </div>

  </div>

  
<% end %>

app/views/authors/posts/_post.html.erb
<tr>
	<td><%= link_to post.title, authors_post_path(post) %></td>
	<td></td>
	<% if post.published? %>
		<td><%= link_to 'Despublicar', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %></td>
	<% else %>
		<td><%= link_to 'Publicar', publish_authors_post_path(post), method: :put,  class: 'btn btn-sm btn-success' %></td>
	<% end %>
	<td><%= link_to 'Editar', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
	<td><%= link_to 'Apagar', authors_post_path(post), method: :delete, data: {confirm: 'Tem certeza que deseja apagar o post?'}, class: 'btn btn-sm btn-danger' %></td>

</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>



<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'Todos os posts') %>
<% provide(:author, 'active') %>


<div class="row">
	<div>
		<%= link_to 'Novo Post', new_authors_post_path, class: 'btn btn-primary btn-lg' %>	
	</div>
	<br/>
	<table class="table table-striped">
		<tr>
			<th colspan="4">Title</th>

		</tr>
		<%= render @posts %>	

	</table>
  
  
</div> 

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, 'active') %>


<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div class="row">
		<%= link_to 'Editar', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
		<%= link_to 'Apagar', authors_post_path(@post), method: :delete, data: {confirm: 'Tem certeza que deseja apagar o post?'}, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row">
	<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
		<h1> <%= @post.title %></h1>
		<p><%= @post.display_day_published %></p>
		<%= @post.body.html_safe%>
		<%= image_tag @post.image.url(:medium) %>
	</div>
</div>