config/routes.rb
Rails.application.routes.draw do

	resources :comments, only: [:index, :create]
	get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  resources :users
  devise_for :authors
  devise_for :models
	root to: 'blog/posts#index'


	#espera que a URL possua /author/posts/new ou algo do tipo
	namespace :authors do
		resources :posts do
			put 'publish' => 'posts#publish', on: :member
			put 'unpublish' => 'posts#unpublish', on: :member
		end
	end

	#não espera que a URL possua nada específico, só recebe o comando e executa
	scope module: 'blog' do
		get 'sobre' => 'pages#sobre', as: :sobre
		get 'contato' => 'pages#contato', as: :contato
		get 'posts' => 'posts#index', as: :posts
		get 'posts/:id' => 'posts#show', as: :post
	end


	
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
	<div class="collapse-bg p-a-1">
		<div class='card'>
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<!-- caioblog.com/blog -->
					<%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
				</li>
				<li class="list-group-item">
					<!-- caioblog.com/Discursões -->
					<%= link_to 'Discussões', comments_path, class: "nav-link #{yield(:disc_active)}" %>
				</li>
				<!-- caioblog.com/sobre -->
				<li class="list-group-item">
					<%= link_to 'Sobre', sobre_path, class: "nav-link #{yield(:sobre_active)}" %>
				</li>
				<!-- caioblog.com/sobre -->
				<li class="list-group-item">
					<%= link_to 'Contato', contato_path, class: "nav-link #{yield(:contato_active)}" %>
				</li>
				<% if author_signed_in? %>
					<li class="list-group-item">
						<%= link_to 'Meus posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
					</li>
					<li class="list-group-item">
						<%= link_to 'Sair', destroy_author_session_path, method: :delete, class: "nav-link" %>
					</li>
				<% end %>
				<% if !author_signed_in? %>
					<li class="list-group-item">
						<%= link_to 'Login', author_session_path, class: "nav-link" %>
					</li>
				<% end %>
					
			</ul>
			
		</div>
	</div>
</div>

<nav class="navbar navbar-light bg-faded">
	<div class='container'>
		<a class='navbar-brand' href='/'>
			Blog do <span class="light">Caio Guedes</span>
		</a>
	<button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
		&#9776;
	</button>
	<ul class="nav navbar-nav ml-auto pull-sm-right hidden-xs-down">
		<li class="nav-item">
			<%= link_to "Blog", root_path, class: "nav-link #{yield(:blog_active)}" %>
		</li>
		<li class="nav-item">
			<%= link_to "Discussões", comments_path, class: "nav-link #{yield(:disc_active)}" %>
		</li>
		<li class="nav-item">
			<%= link_to "Sobre", sobre_path, class: "nav-link #{yield(:sobre_active)}" %>
		</li>
		<li class="nav-item">
			<%= link_to "Contato", contato_path, class: "nav-link #{yield(:contato_active)}" %>
		</li>
		<% if author_signed_in? %>

			<li class="nav-item">
				<%= link_to 'Meus posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
			</li>
			<li class="nav-item">
				<%= link_to 'Sair', destroy_author_session_path, method: :delete, class: "nav-link" %>
			</li>
		<% end %>
		<% if !author_signed_in? %>
			<li class="nav-item">
				<%= link_to 'Login', author_session_path, class: "nav-link" %>
			</li>
		<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Blog do Caio Guedes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>

  </head>

  <body>

  	<%= render 'layouts/navbar' %>
    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %> 
  	<div class="container <%= controller_name %> <%= action_name %>">
    <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Blog do Caio Guedes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
  	<div class="container <%= controller_name %> <%= action_name %>">
    <%= yield %>
    </div>
  </body>
</html>